Refactor GitHub workflow to remove SonarCloud scan step

diff --git a/.github/workflows/check-and-deploy.yaml b/.github/workflows/check-and-deploy.yaml
--- a/.github/workflows/check-and-deploy.yaml
+++ b/.github/workflows/check-and-deploy.yaml
@@ -54,10 +54,17 @@ jobs:
       - name: Build
         run: npm run build
 
+      - name: Check Netlify Credentials
+        run: |
+          if [ -z "${{ secrets.NETLIFY_AUTH_TOKEN }}" ] || [ -z "${{ secrets.NETLIFY_SITE_ID }}" ]; then
+            echo "Error: Netlify credentials not provided. Please set NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID secrets in your repository settings."
+            exit 1
+          fi
+
       - name: Deploy to Netlify
         uses: nwtgck/actions-netlify@v3.0
         with:
-          publish-dir: './dist'
+          publish-dir: ./dist
           production-branch: master
           github-token: ${{ secrets.GITHUB_TOKEN }}
           deploy-message: "Deploy Preview from PR"
@@ -67,4 +74,4 @@ jobs:
         env:
           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
-        timeout-minutes: 1
+        timeout-minutes: 5
